steps:
  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-northeast1-docker.pkg.dev/testing-baksara/graphql-api/graphql-api",
        ".",
      ]

    env:
      - "DB_DATABASE=$$DB_DATABASE_DEVELOPMENT"
      - "DB_HOST=$$DB_HOST"
      - "DB_PASSWORD=$$DB_PASSWORD"
      - "DB_SOCKET_PATH=$$DB_SOCKET_PATH"
      - "DB_USERNAME=$$DB_USERNAME"

  # Push the Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia-northeast1-docker.pkg.dev/testing-baksara/graphql-api/graphql-api"]

  # Configure Docker for Artifact Registry using gcloud
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["auth", "configure-docker", "asia-northeast1-docker.pkg.dev"]

  # Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "graphql-api",
        "--set-cloudsql-instances",
        "testing-baksara:asia-southeast2:baksara",
        "--image",
        "asia-northeast1-docker.pkg.dev/testing-baksara/graphql-api/graphql-api",
        "--platform",
        "managed",
        "--region",
        "asia-northeast1",
      ]

substitutions:
  _DB_DATABASE_DEVELOPMENT: ${{ secrets.DB_DATABASE_DEVELOPMENT }}
  _DB_HOST: ${{ secrets.DB_HOST }}
  _DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  _DB_SOCKET_PATH: ${{ secrets.DB_SOCKET_PATH }}
  _DB_USERNAME: ${{ secrets.DB_USERNAME }}
